---
- name: Install prerequisite packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    allow_unauthenticated: false
  loop: "{{ prereq_pkgs }}"
  become: true

- name: Install crio repo keyrings
  ansible.builtin.apt_key:
    url: "{{ item.url }}"
    keyring: "{{ item.file }}"
    state: present
  loop: "{{ crio_keyrings }}"
  become: true

- name: Add crio repositories
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    state: present
    mode: "0644"
    filename: "{{ item.filename }}"
    update_cache: true
    validate_certs: true
  loop: "{{ crio_repos }}"
  become: true

- name: Install cri-o packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    allow_unauthenticated: false
    update_cache: true
  loop: "{{ crio_pkgs }}"
  become: true
  notify:
    - crio | systemctl start crio
...
