---
- name: crio | systemctl restart systemd-modules-load.service
  service:
    name: "systemd-modules-load.service"
    state: "restarted"
  changed_when: no
  ignore_errors: yes

- name: crio | sysctl --system
  command: sysctl --system
  changed_when: no
  ignore_errors: yes

- name: crio | systemctl daemon-reload
  systemd:
    daemon_reload: yes
  changed_when: no
  ignore_errors: yes
...
