---
- name: crio | systemctl restart systemd-modules-load.service
  ansible.builtin.service:
    name: "systemd-modules-load.service"
    state: "restarted"
  become: yes
  changed_when: no

- name: crio | sysctl --system
  ansible.builtin.command: sysctl --system
  become: yes
  changed_when: no

- name: crio | systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes
  changed_when: no

- name: crio | systemctl start crio
  ansible.builtin.systemd:
    name: crio
    state: started
    enabled: yes
  become: yes
  changed_when: no
...
