---
- name: crio | systemctl restart systemd-modules-load.service
  ansible.builtin.service:
    name: "systemd-modules-load.service"
    state: "restarted"
  become: true
  changed_when: false

- name: crio | sysctl --system
  ansible.builtin.command: sysctl --system
  become: true
  changed_when: false

- name: crio | systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  changed_when: false

- name: crio | systemctl start crio
  ansible.builtin.systemd:
    name: crio
    state: started
    enabled: true
  become: true
  changed_when: false
...
